---
title: "Asthma Data Preparation I - Data Processing Strategy"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
---

## Introduction

Before commencing the project, it is a good idea to have a path towards efficiently acquiring and processing data, given the amount of it to be processed.

Main Page: https://www.cdc.gov/asthma/brfss/

Archive pages: https://www.cdc.gov/asthma/brfss/archive.htm

Note on the data: 
* The separate aggregation is slightly annoying, because the links between the different
* groups are broken - can't get combinations e.g. age, sex and state!
* Data is pre-stratified! --> possibly to deal with missin data

Therefore, it is a good idea to get multiple tables from multiple years, to represent different slices/perspectives of the data over time. This is reasonable, given that we don't know beforehand which slices will prove most useful. Blending the data may not be feasible, given that the data has <u>apparently</u> already been split and aggregated with no direct connections to the individual observations from which the data was drawn :disappointed:.

## Current Data: 2011 to 2014

### Overview

Looking at the data pertaining to this period of time, we notice that the base URL is:

<pre><b>https://www.cdc.gov/asthma/brfss/</b></pre>

The next component of the table is the **year** segment, followed by some sort of table designation:

Example: 

<pre>
* 2014 Adult Lifetime Asthma by Age: https://www.cdc.gov/asthma/brfss/2014/tableL3.htm
* 2014 Child Lifetime Asthma by Age: https://www.cdc.gov/asthma/brfss/2014/child/tableL3.htm
</pre>

Now, the first issue is that the adult and child tables have an important difference in the **child** segment of the URL, which is important to keep in mind.

The adult tables are divided into the following interesting segments:

* Gender (percent)
* Age group
* Race/Ethnicity (seems more informative than simply by Race)
* Education
* Income

However, the child tables only contain the following groups of interest:

* Gender (percent)
* Age group
* Race/Ethnicity

If we want to look at the potential trends in both datasets (and we do), we need to bear this in mind. Note that **education** and **income** data were not made available, presumably not collected.

Further, the datasets are split into two different measures, **lifetime** and **current**, which are defined in the [background information](https://www.cdc.gov/asthma/brfss/default.htm) as follows:

> **Lifetime** _asthma_ is defined as an affirmative response to the question “Have you ever been told by a doctor {nurse or other health professional} that you have asthma?”.
        
> **Current** _asthma_ is defined as an affirmative response to that question followed by an affirmative response to the subsequent question “Do you still have asthma?”.

Basically, these definitions equate to: 

* **lifetime**: used to have asthma at one time.
* **lifetime**: still have asthma now.

### Adult vs Child

Now that we have this background, lets get back to the table URLs. From the examples above, using 2014, we can generalise these "base" URL segments:

<pre>
* 2014 Adult: https://www.cdc.gov/asthma/brfss/<b>2014</b>/ ...
* 2014 Child: https://www.cdc.gov/asthma/brfss/<b>2014</b>/child/ ...
</pre>

to the following: 

<pre>
* base Adult: https://www.cdc.gov/asthma/brfss/<b>yearID</b>/ ...
* base Child: https://www.cdc.gov/asthma/brfss/<b>yearID</b>/child/ ...
</pre>

Basically, **yearID** is a placeholder for any year between 2011 and 2014 (inclusive).

Now we can process the 

### Demographic attributes

The demographic IDs for the attributes of interest are listed as follows:

| Demographic      | ID |
|------------------|:--:|
| Gender (percent) | 21 |
| Age              | 3  |
| Race/Ethnicity   | 5  |
| Education        | 6  |
| Income           | 7  |

Basically, these attribute names and IDs are, fortunately, identical for both adults and children. Let's call the demographic IDs **demID**, both for brevity and because this sounds like a good name for a variable :wink:. So, if we want to refer to demographic statistics for age for lifetime and current asthma, respectively, we can do so as follows:

* Lifetime: L**demID**
* Current: C**demID**

Lets consider current and lifetime as measures of asthma **recency**, we can call this variable **recID** and generalise the above situations to:

* **recIDdemID**

The best thing about this scenario is that because these demographic attributes are identical for both adults and children, they can be handled the same way :)

### Putting the pieces together

The analysis of the data sources above allows us to understand how to start the systematic acquisition and processing of the raw data pertaining to asthma prevalence for the period of time specified. Thus, during the period covering 2011 to 2014, the locations of tables for adults and children can be generalised as follows:

* generalised adult table: baseURL**/****yearID****/**table**recIDdemID**.htm/
* generalised child table: baseURL**/****yearID****/**child**/**table**recIDdemID**.htm/

This basically mean that we can write code to efficiently obtain all of the information for all of the tables that we require for both adults and children for the years between 2011 and 2014 (latest avaiable as at 04/02/2017) :smile:!

## Archive Data: 1999 to 2010

There is a slight difference between the the URLs of the current data and those of the archive datasets. Looking back, I realised that the child data only exists from the year **2001** onwards. This has implications for input validation to prevent attempts to retrieve child data from before that point. In addition, child data from between 2001 and 2004 exists only as woefully incomplete aggregate (overall) tables. Essentially, child data is only useful from about **2005** onwards, and is **not** worth the effort of importing previous years that will be discarded during subsequent data cleaning steps. 

This brings up an interesting decision. The adult dataset seems valid from 1999 (earliest record year) till the end of the data series in 2014. However, since part of the aim is to combine the adult and child datasets as part of some of the analyses, is it worth bothering with any data, adult or child, prior to 2005? Remembering that we have 15 and 9 years worth of data if we begin in 1995 and 2005, respectively. Fortunately, this is a relatively trivial question given how we intend to process the data in question.

The links below highlight the main differences and similarities between the archive URLs, which can be further compared to the more recent data.

### 2010

<pre>
https://www.cdc.gov/asthma/brfss/2010/lifetime/tableL3.htm
https://www.cdc.gov/asthma/brfss/2010/child/lifetime/tableL3.htm

https://www.cdc.gov/asthma/brfss/2010/current/tableC3.htm
https://www.cdc.gov/asthma/brfss/2010/child/current/tableC3.htm
</pre>

### 1999 to 2009

<pre>
https://www.cdc.gov/asthma/brfss/09/lifetime/tableL3.htm

https://www.cdc.gov/asthma/brfss/09/current/tableC3.htm

https://www.cdc.gov/asthma/brfss/05/child/current/tableC3.htm
</pre>

* The first thing to note is that the asthma recency and demographic data type designations are identical to those in the "current dataset". This is good because we can use the same table to automate data import.

* The next thing is that the URL suffixes for adult (**current/tableL3.htm**) and child (**/child/current/tableL3.htm**) tables have changed slightly from those in the current data series. This, naturally, alters the logic required to process the data.

* The next change is that years prior to 2010, are included in the **2 digit** year format. This is a trivial problem, but important to note to avoid needless grief.

Without going into any detail, the logic presented in the previous section can be adapted to cover these variations. However, separate implemetation of this logic, preferably as a separate function, is advised to avoid the construction of needlessly complicated code.

### Number vs. Percent

During the process of inspecting the data I looked at the structure of the data to see what I was in for, i.e. what variables would I need to extract from the data after harvesting them from the web.

It then dawned upon me that the state of the data was not quite what I thought it was. Basically, the *Sample size* variable is somehow used to create the *Prevalence
(percent)* variable. This would make sense, given that the prevalence would simply be the _number of asthma sufferers **in the study**_ <u>divided by</u> the sample size. 

Oddly, or so it would seem, the *Prevalence (number)* variable seems to be a calculation of the _number of asthma sufferers **in the regional population**_ using the *Prevalence
(percent)* variable and the **total** population of the region in question.

This wasn't as problematic as I might have thought, because it is a simple matter to derive (i.e. estimate) either the **total population** or the **asthma sufferes in sample** as indicated in the above paragraphs. However, without knowledge of the method of calculation, such derivative variables would always be tenuous in part because:

* they would always be an estimate of the actual parameter, as any "adjustments" would be hidden
* *Prevalence(percent)* is the key variable, since some sort of ratio or proportion would be required for some modelling or machine learning applications.
* such an estimate is easily obtained where needed, with the caveats mentioned.

That said, I figured that it would be useful to add the Overall data table to the list of data to obtain. Fortunately, this is as simple as including this entry in the demographic attributes table defined in a previous section:

| Demographic      | ID |
|------------------|:--:|
| Overall          |  1 |

This gives the updated table below:

| Demographic      | ID |
|------------------|:--:|
| Overall          |  1 |
| Gender (percent) | 21 |
| Age              | 3  |
| Race/Ethnicity   | 5  |
| Education        | 6  |
| Income           | 7  |

With this updated table, we can now programmatically reconstruct all of the URLs that we need to use in order to connect to anc acquire the data that we will use for analysis.

Incidentally, this demographic ID table is an example of a [metadata](https://en.wikipedia.org/wiki/Metadata) table, specifically a form of "structural" metadata. Personally, I am a fan of metadata tables such as this as they make research more automatable, and thus reproducible. 

Basically, one has to simply update the metadata table by adding data that can be constructed to process data that conforms to the same rules as the other entries in the same table. This has the benefit of providing an overall picture of what kind of information is being represented, given the similar processing that all rows will receive :wink". It also makes data management far more useful as one can keep track of the data analysis inputs.

## Next Steps

In order to carry out this strategy I would need to employ web scraping tools such as [rvest](https://blog.rstudio.org/2014/11/24/rvest-easy-web-scraping-with-r/) in combination with the knowledge gained above to generate script(s) to acquire and process the data for further analysis.

The [next section](https://github.com/drbulu/healthyAir_DSc_proj/blob/master/01_Data_Prep/asthma_data_source_prep_02.Rmd) describes how I used the strategy described in this document to create the code needed to harvest the Asthma data from the URLs.

<b style="color:red;">Future Note:</b> I also need to check the footnotes of each table in order to understand any caveats (i.e. "surprises" :wink:!) relating to the different datasets.

<br/>